# Generated by Django 5.1.6 on 2025-03-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tmax', models.FloatField(null=True)),
                ('tmin', models.FloatField(null=True)),
                ('prcp', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'climate_data2020_2024',
                'managed': False,
            },
        ),
    ]
